version: '3'

services:
  frontend:
    build: frontend
    restart: unless-stopped
  
  backend:
    build: backend
    restart: unless-stopped
    env_file: .env

  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./db/data/db:/data/db

  nginx:
    build: nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - db
    ports:
      - 82:80
      - 1935:1935
